version: '3.5'

services:
    db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: MisakoUno01*
            POSTGRES_DB: decathlon_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
